### PR TITLE
add django as a requirement, pin to 1.11 for now

### PR DESCRIPTION
**Pull request by barentine**
see python-microscopy issue [#160](https://github.com/python-microscopy/python-microscopy/issues/160), working towards migrating to cluster of one

### CODE REVIEW

**Comment by David-Baddeley** [comment]
we now have a workaround so that things run without django. I'd prefer to leave django as a soft dependency to make resolving a workable environment easier.

**Comment by barentine** [comment]
where do we land on this now that we want to run clusterUI on an executable install for the demo @David-Baddeley ?

**Comment by barentine** [comment]
note that 1.11 probably isn't the version to aim for now.
```
conda install django=1.11
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                            

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - django=1.11 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

```

**Comment by David-Baddeley** [comment]
Look at the current pyme-depends, think I already have it pinned at 2.2
(maybe 2.1). Can double check.

Cheers,
David

**Comment by barentine** [comment]
yeah, thanks, saw 2.1 and was just giving that a go

**Pull request closed without merging**
